# Generated by Django 5.2.7 on 2025-10-19 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название скважины')),
                ('area', models.CharField(max_length=100, verbose_name='Наименование участка')),
                ('structure', models.CharField(max_length=100, verbose_name='Наименование сооружения')),
                ('start_date', models.DateField(verbose_name='Дата начала бурения')),
                ('end_date', models.DateField(verbose_name='Дата окончания бурения')),
                ('planned_depth', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Проектная глубина, м')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('drilling_method', models.CharField(choices=[('rotary', 'Ротационное бурение'), ('auger', 'Шнековое бурение'), ('percussion', 'Ударно-канатное бурение'), ('core', 'Колонковое бурение')], max_length=20, verbose_name='Способ бурения')),
                ('drilling_rig', models.CharField(max_length=100, verbose_name='Буровая установка')),
                ('vehicle', models.CharField(max_length=100, verbose_name='Транспортное средство')),
                ('diameter', models.CharField(max_length=50, verbose_name='Диаметр бурения, мм')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Геолог')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeologyLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_number', models.IntegerField(verbose_name='Номер слоя')),
                ('depth_from', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Глубина от, м')),
                ('depth_to', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Глубина до, м')),
                ('lithology', models.CharField(choices=[('sand', 'Песок'), ('clay', 'Глина'), ('loam', 'Суглинок'), ('sandy_loam', 'Супесь'), ('peat', 'Торф'), ('gravel', 'Гравий'), ('boulder', 'Валуны'), ('fill', 'Насыпной грунт')], max_length=20, verbose_name='Литология')),
                ('description', models.TextField(verbose_name='Описание грунта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='drilling_log.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Геологический слой',
                'verbose_name_plural': 'Геологические слои',
                'ordering': ['well', 'depth_from'],
                'unique_together': {('well', 'layer_number')},
            },
        ),
    ]
