# Generated by Django 5.2.7 on 2025-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название скважины')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
