# Generated by Django 5.2.7 on 2025-10-17 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название скважины')),
                ('field', models.CharField(max_length=100, verbose_name='Месторождение')),
                ('location', models.CharField(max_length=200, verbose_name='Координаты')),
                ('planned_depth', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Плановая глубина, м')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('drilling', 'В процессе бурения'), ('completed', 'Завершена'), ('abandoned', 'Ликвидирована')], default='planned', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала бурения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LithologySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_from', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Глубина от, м')),
                ('depth_to', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Глубина до, м')),
                ('rock_type', models.CharField(choices=[('clay', 'Глина'), ('sand', 'Песок'), ('silt', 'Алевролит'), ('limestone', 'Известняк'), ('dolomite', 'Доломит'), ('sandstone', 'Песчаник'), ('shale', 'Аргиллит'), ('coal', 'Уголь'), ('conglomerate', 'Конгломерат'), ('breccia', 'Брекчия'), ('tuff', 'Туф'), ('other', 'Другое')], max_length=20, verbose_name='Тип породы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('hardness', models.CharField(blank=True, max_length=50, verbose_name='Твердость')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Дополнительные заметки')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отбора')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Геолог')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='drilling_log.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Литологическая проба',
                'verbose_name_plural': 'Литологические пробы',
                'ordering': ['well', 'depth_from'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('drilled_meters', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Пробурено за день, м')),
                ('current_depth', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Текущая глубина, м')),
                ('drilling_time', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Время бурения, часов')),
                ('remarks', models.TextField(blank=True, verbose_name='Примечания и наблюдения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отчет составил')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='drilling_log.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Дневной отчет',
                'verbose_name_plural': 'Дневные отчеты',
                'ordering': ['-date', 'well'],
                'unique_together': {('well', 'date')},
            },
        ),
    ]
